resources:
  - name: PS_Sync_9756_res
    type: GITRepo
    configuration:
      path: {{.jfrog-pipelines.sourceRepository}}
      gitProvider: s_gitHub
      branches:
        include: {{gitBranch}}
pipelines:
  - name: PS_Sync_9756
    steps:
      - name: PS_Sync_9756
        type: Bash
        configuration:
          inputResources:
            - name: PS_Sync_9756_res
          
        execution:
          onStart:
            - task: jfdev-ci-commons/setup-step-commons@v0.0.1
