
pipelines:
  - name: PS_SYNC_10509_001
    steps:
      - name: PS_SYNC_10509_001
        type: Bash
        configuration:
          inputResources:
            - name: pipeline_trigger_10509
        execution:
          onExecute:
            - echo "test"
