resources:
  - name: PS_Sync_9756_res
    type: GITRepo
    configuration:
      path: {{.jfrog-pipelines.sourceRepository}}
      gitProvider: goithub
      branches:
        include: {{gitBranch}}
pipelines:
  - name: PS_Sync_9756
    steps:
      - name: PS_Sync_9756
        type: Bash
        configuration:
          inputResources:
            - name: PS_Sync_9756_res
          integrations:
            - name: goithub
            - name: jfrogPlatformToken  
          
        execution:
          onStart:
            - task: jfrog/setup-go@latest
