resources:
  - name: PS_Sync_9756_res
    type: GITRepo
    configuration:
      path: {{.jfrog-pipelines.sourceRepository}}
      gitProvider: goithub
      branches:
        include: {{gitBranch}}

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: PS_Sync_9756
    configuration:
      integrations:
        - name: s_gitHub
    steps:
      - name: PS_Sync_9756
        type: Bash
        configuration:
          inputResources:
            - name: PS_Sync_9756_res
          outputResources:
            - name: propertyBag
          integrations:
            - name: goithub
            - name: jfrogPlatformToken
            - name: slackIntegration
        execution:
          onExecute:
            - ls
            - task: jfdev-ci-commons/setup-step-commons@v0.0.1
            
            
