pipelines:
  - name: pipeline_MB_G_002
    steps:
      - name: MB_G_002_step1
        type: Bash
        configuration:
          outputResources:
            - name: MB_G_002_outputResource
              branch: master
        execution:
          onExecute:
            - write_output MB_G_002_outputResource updatedBy=MB_G_002_step1
      - name: MB_G_002_step2
        type: Bash
        configuration:
          inputResources:
            - name: MB_G_002_outputResource
              branch: master
            - name: MB_G_002_inputResource
              branch: master
        execution:
          onExecute:
            - if [ "$res_MB_G_002_inputResource_test" != "MB_G_002" ]; then return 1; fi
            - if [ "$res_MB_G_002_outputResource_updatedBy" != "MB_G_002_step1" ]; then return 1; fi
