resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: nitind123/newTemplates
      gitProvider: nitind
      branches:
        include: submodule_provate
      recurseSubmodules: true

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    configuration:
      integrations:
        - name: nitind
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          outputResources:
            - name: propertyBag
          integrations:
            - name: nitind
        execution:
          onExecute:
            - pushd $res_myRepo_resourcePath
            - ls
            - write_output propertyBag "foo=$run_number"
