valuesFilePath: ./values.yml

# include:
#   template: jfrog/NpmCI/1.0.0

resources:
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.gitIntegration }}
      branches:
        include: {{ .Values.repo.branchPattern | default "main" }}
 
{{ if .Values.publishBuild }}
  - name: {{ .Values.namePrefix }}_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
 
  - name: {{ .Values.namePrefix }}_spec
    type: FileSpec
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
      pattern: '{{ .Values.buildSpecPattern | default "*" }}'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}
{{ end }}
 
 
pipelines:
  - name: {{ .Values.namePrefix }}_npm_ci
    configuration:
      affinityGroup: {{ .Values.namePrefix }}_npm_ci
    {{ if .Values.publishBuild }}
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NAME: ${pipeline_name}
          JFROG_CLI_BUILD_NUMBER: ${run_id}
    {{ end }}
    steps:
      - name: build
        type: NpmBuild
        configuration:
          integrations:
            - name: {{ .Values.artIntegration }}
          inputResources:
            - name: {{ .Values.namePrefix }}_repo
 
        {{ if .Values.npmConfig.npmArgs }}
          npmArgs: {{ .Values.npmConfig.npmArgs }}
        {{ end }}
        {{ if .Values.npmConfig.sourceLocation }}
          sourceLocation: {{ .Values.npmConfig.sourceLocation }}
        {{ end }}
        {{ if .Values.npmConfig.resolverRepo }}
          resolverRepo: {{ .Values.npmConfig.resolverRepo }}
        {{ end }}
 
      - name: publish
        type: NpmPublish
        configuration:
          integrations:
            - name: {{ .Values.artIntegration }}
          inputSteps:
            - name: build
        {{ if .Values.publishBuild }}
          outputResources:
            - name: {{ .Values.namePrefix }}_info
            - name: {{ .Values.namePrefix }}_spec
        {{ end }}
        {{ if .Values.publishBuild }}
          autoPublishBuildInfo: true
        {{ end }}
        {{ if and .Values.scanBuild .Values.publishBuild }}
          forceXrayScan: true
        {{ end }}
        {{ if .Values.npmConfig.deployerRepo }}
          deployerRepo: {{ .Values.npmConfig.deployerRepo }}
        {{ end }}
      {{ if .Values.publishBuild }}
        execution:
          onSuccess:
            - write_output {{ .Values.namePrefix }}_spec buildName="${JFROG_CLI_BUILD_NAME}"
            - write_output {{ .Values.namePrefix }}_spec buildNumber="${JFROG_CLI_BUILD_NUMBER}"
      {{ end }}
