pipelines:
  - name: P_PS_11836_001
    steps:
      - name: P_PS_11836_001_step_1
        type: Bash
        configuration:
          integrations:
            - name: wrong_s_artifactory
            - name: s_artifactory
        execution:
          onExecute:
            - echo "test"
