resources:
  - name: P_WF_7379_001
    type: PropertyBag
    configuration:
      property: value

  - name: ES-resource-0001-valid
    type: shippable/GitRepo
    syntaxVersion: 1.0.0
    configuration:
      name: test
  - name: ES-resource-0001
    type: shippable/GitRepo
    syntaxVersion: 1.11.11
    configuration:
      name: test     

pipelines:
  - name: pipeline_P_WF_7379_001
    steps:
      - name: P_WF_7379_001
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_7379_001
        execution:
          onExecute:
            - echo "Testing..."
            
            
