



resources:
  - name: P_WF_7379_001
    type: PropertyBag
    configuration:
      property: value
 - name: testResource
    type: test/TestResource
    configuration:
      foo: bar
      sourceArtifactory: s_artifactory
      gitProvider: s_gitHub

  
pipelines:
  - name: pipeline_P_WF_7379_001
    steps:
      - name: P_WF_7379_001
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_7379_001
        execution:
          onExecute:
            - echo "Testing..."
            
            
