resources:
  - name: P_WF_7379_001
    type: PropertyBag
    configuration:
      property: value

  GitRepo:
  name: fooGitRepo
  gitProvider: s_gitHub
  path: {{.jfrog-pipelines.sourceRepository}}
  branches:
    include: 'master'

artifactoryIntegration: s_artifactory
  
Image:
  name: fooImage
  sourceRepository: foo

DockerBuild:
  name: foobuild
  dockerImageName: foo
  dockerFileName: foo
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

Pipeline:
  name: foo

DockerPush:
  name: foopush
  dockerImageName: foo
  dockerFileName: foo
  targetRepository: foo  

pipelines:
  - name: pipeline_P_WF_7379_001
    steps:
      - name: P_WF_7379_001
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_7379_001
        execution:
          onExecute:
            - echo "Testing..."
            
            
