resources:
  - name: A_pipeline_11878_res
    type: PropertyBag
    configuration:
      key1: value1
pipelines:
  - name: A_pipeline_11878
    configuration:
      environmentVariables:
        readOnly:
          pipelineEnv:
            secure: false
            default: "somePipValue"
    steps:
      - name: S_A_pipeline_11878
        type: Bash
        configuration:
          environmentVariables:
            mySecureEnv:
              allowCustom: true
              secure: false
              default: "someValue"
          inputResources:
            - name: A_pipeline_11878_res
        execution:
          onExecute:
            - echo "executing"
