resources:
  - name: PS_Sync_9756_res
    type: GITRepo
    configuration:
      path: {{.jfrog-pipelines.sourceRepository}}
      gitProvider: s_gitHub
      branches:
        include: {{gitBranch}}
      recurseSubmodules: true

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: PS_Sync_9756
    configuration:
      integrations:
        - name: s_gitHub
    steps:
      - name: PS_Sync_9756
        type: Bash
        configuration:
          inputResources:
            - name: PS_Sync_9756_res
          outputResources:
            - name: propertyBag
          integrations:
            - name: s_gitHub
        execution:
          onExecute:
            - pushd $res_myRepo_resourcePath
            - |
              if ./somecommand | grep -q 'string'; then
                echo "matched"
              fi
