pipelines:
  - name: CleanHelmDeploymentNoPromo
    configuration:
      environmentVariables:
        readOnly:
          RELEASE_NAME: 'simplehelm-test-no-promotion'
          K8S_NAMESPACE: "pipe-master-pool"
    steps:
      - name: CleanHelmResourceNoPromo
        type: Bash
        configuration:
          integrations:
            - name: s_kubernetes
        execution:
          onExecute:
            - helm3 delete ${RELEASE_NAME} --namespace $K8S_NAMESPACE
