template: true
pipelines:
  - name: P_SYC_Pipelines_10388_001_pipe
    steps:
      - name: P_SYC_Pipelines_10388_001_addition_dict_function_support
        type: Bash
        execution:
          onExecute:
            - echo {{ $myDict := dict "name1" "value1" "name2" "value2" "name3" "value 3" }}
            - echo {{ get $myDict "name1" }}
      - name: P_SYC_Pipelines_10388_002_addition_list_function_support
        type: Bash
        configuration:
          inputSteps:
            - name: P_SYC_Pipelines_10388_001_addition_dict_function_support
        execution:
          onExecute:
            - echo {{ $myList := list 1 2 3 4 5 6 7 8 }}
            - echo {{ chunk 3 $myList }}