
pipelines:
  - name: P_files
    steps:
      - name: S_files
        type: Bash
        configuration:
          environmentVariables:
            env1: gitbranch
            env2: sourceRepository
        execution:
          onExecute:
            - echo 'test'
