{{- define "pipe.additionalEnvs" -}}
env3: additional
  {{ end -}}
pipelines:
  - name: P_files
    steps:
      - name: S_files
        type: Bash
        configuration:
          environmentVariables:
            env1: gitbranch
            env2: sourceRepository
            {{ include "pipe.additionalEnvs" . }}
            helperName: {{ include "sanity.name" . }}
        execution:
          onExecute:
            - echo {{ get (.Files.Get "config.yml" | fromYaml) "message11" }}
