resources:
  - name: testResource
    type: test/TestResource
    configuration:
      foo: bar
      sourceArtifactory: s_artifactory
      gitProvider: s_pipeAutoSCM

pipelines:
 - name: PipelineExtension_automation
   steps:
      - name: step1
        type: Bash
        configuration:
           inputResources:
            - name: testResource
        execution:
          onExecute:
            - echo "$res_testResource_sourceArtifactory_url"
            - echo "$res_testResource_gitProvider_url"
            - |
              if [ "$res_testResource_gitProvider_url" != "https://bitbucketapsnew.jfrogdev.org" ]; then
               exit 1
              fi
