pipelines:
  - name: PS_Sync_9494_003
    steps:
      - name: PS_Sync_9494_003_001
        type: Bash
        execution:
          onExecute:
            - cd /tmp
            - mkdir -p "node_modules/@jfrog-pipelines"
            - echo "test" >> node_modules/@jfrog-pipelines/test.txt
            - add_pipeline_files node_modules/@jfrog-pipelines jfrog_pipelines_packages_cache
      - name: PS_Sync_9494_003_002
        type: Bash
        configuration:
          inputSteps:
            - name: PS_Sync_9494_003_001
        execution:
          onExecute:
            - cd /tmp
            - mkdir -p "target/node_modules"
            - cd target
            - restore_pipeline_files jfrog_pipelines_packages_cache node_modules/
      - name: branch_environment
        type: Jenkins
        configuration:
          inputSteps:
            - name: PS_Sync_9494_003_001
              status:
                - success
                - skipped
          integrations:
            - name: i_testJenkins
          jenkinsJobName: tools/platform/environment_operate
          buildParameters:
            SERVER_NAME: ${res_environmentOperateBag_serverName}
            EXPIRY: "3d"
            ACTION: "upgrade"
