resources:
  - name: pipeline_trigger_105091
    type: Artifact
    configuration:
      jfrogPlatformProvider: jfrogAccessToken_10509
      repositories:
        - test-automation-generic-local
      artifactPath:
        include:
          - tools/*
        exclude:
          - exclude/*
      buildOn:
        deployed: true
        cached: true
        deleted: true
        copied: true
        moved: true
      branches:
        include: feature/PIPE-10509
        exclude: test
pipelines:
  - name: PS_SYNC_10509_001
    steps:
      - name: PS_SYNC_10509_001
        type: Bash
        configuration:
          inputResources:
            - name: pipeline_trigger_105091
        execution:
          onExecute:
            - echo "test"
