resources:
  - name: myFirstRepo1
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}
        
pipelines:
  - name: Ps_variable
    steps:
      - name: build
        type: PowerShell
        configuration:
          environmentVariables:
            env1: value1
            env2:
              default: value2
              description: Example Variable
              values:
                - value2
                - value3
              allowCustom: false
          inputResources:
            - name: myFirstRepo1    
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "10.18"      
        execution:
          onExecute:
            - Push-Location $res_src_resourcePath
            - npm install
       
