pipelines:
  - name: Ps_variable
    steps:
      - name: build
        type: PowerShell
        configuration:
          environmentVariables:
            env1: value1
            env2:
              default: value2
              description: Example Variable
              values:
                - value2
                - value3
              allowCustom: false
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "10.18"
        execution:
          onExecute:
            - Push-Location $res_src_resourcePath
            - npm install
       
