template: true

resources:
  - name: S_GoPublishBinary_0025_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

  - name: S_GoPublishBinary_0025_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: goBuild
    steps:
      - name: S_GoPublishBinary_0025_1
        type: GoBuild
        configuration:
          inputResources:
            - name: S_GoPublishBinary_0025_GitRepo
          integrations:
            - name: s_artifactory
          sourceLocation: "tests/Go/HelloWorld"
          resolverRepo: test-automation-go-virtual
      - name: S_GoPublishBinary_0025_2
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: S_GoPublishBinary_0025_1
          integrations:
            - name: s_artifactory
          outputResources:
            - name: S_GoPublishBinary_0025_BuildInfo
          targetRepository: test-automation-go-local
          autoPublishBuildInfo: true
