

resources:
  - name: S_PS_HelmDeploy_BuildInfo_8309_006
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: helmbuild
      buildNumber: 1

  - name: S_PS_HelmDeploy_GitRepo_8309_006
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: master

  - name: S_PS_HelmDeploy_ReleaseBundle_8309_006
    type: ReleaseBundle
    configuration:
      sourceDistribution: s_distribution
      name: name
      version: '1'

pipelines:
  - name: S_PS_HelmDeploy_8309_006
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          release_name_from_repo: "simplehelm-from-repo"
          k8s_namespace: "pipe-master-pool"
      nodePool: win_2019
    steps:
      - name: S_PS_HelmDeploy_8309_006_create_build
        type: PowerShell
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: S_PS_HelmDeploy_GitRepo_8309_006
          outputResources:
            - name: S_PS_HelmDeploy_BuildInfo_8309_006
        execution:
          onExecute:
            - add_run_variables JFROG_CLI_BUILD_NUMBER=${run_id}
            - Push-Location ${res_S_PS_HelmDeploy_GitRepo_8309_006_resourcePath}/yaml/core/helmdeploy
            - jfrog rt upload simplehelm-0.3.0.tgz "simplecharts/S_PS_HelmDeploy_8309_006/"
            - jfrog rt bce $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output S_PS_HelmDeploy_BuildInfo_8309_006 buildName=$JFROG_CLI_BUILD_NAME buildNumber=$JFROG_CLI_BUILD_NUMBER

      - name: Create_Bundle
        type: CreateReleaseBundle
        configuration:
          integrations:
            - name: s_artifactory
          releaseBundleName: S_PS_HelmDeploy_BuildInfo_8309_006_bundle
          releaseBundleVersion: ${run_id}
          dryRun: false
          sign: true
          inputResources:
            - name: S_PS_HelmDeploy_BuildInfo_8309_006
          outputResources:
            - name: S_PS_HelmDeploy_ReleaseBundle_8309_006

      - name: deploy_helm_chart_from_helm_repo
        type: HelmDeploy
        configuration:
          integrations:
            - name: s_artifactory
            - name: s_kubernetes
          inputResources:
            - name: S_PS_HelmDeploy_ReleaseBundle_8309_006
          helmVersion: 3
          releaseName: ${release_name_from_repo}
          chartPath: simplecharts/S_PS_HelmDeploy_8309_006
          chartName: simplehelm
          chartVersion: 0.3.0
          flags: "--force --wait --timeout 900s --set image.repository=trriplejay/simplehelm --set image.tag=latest"
          valueFilePaths:
            - values.yaml
          lint: true
          lintFlags: "--strict"
          test: true
        execution:
          onComplete:
            - |
              Write-Output "Deleting release bundle..."
              $distributionUrl = $res_S_PS_HelmDeploy_ReleaseBundle_8309_006_sourceDistribution_url
              $distributionUser = $res_S_PS_HelmDeploy_ReleaseBundle_8309_006_sourceDistribution_user
              $distributionPassword = $res_S_PS_HelmDeploy_ReleaseBundle_8309_006_sourceDistribution_apikey
              jfrog config add distribution --overwrite --insecure-tls=$no_verify_ssl --distribution-url $distributionUrl --user $distributionUser --password $distributionPassword --interactive=false
              jfrog config use distribution
              $releaseBundleName = (find_resource_variable "S_PS_HelmDeploy_ReleaseBundle_8309_006" name)
              $releaseBundleVersion = (find_resource_variable "S_PS_HelmDeploy_ReleaseBundle_8309_006" version)
              jfrog ds release-bundle-delete --delete-from-dist=true --insecure-tls=$no_verify_ssl $releaseBundleName $releaseBundleVersion
              jfrog config remove distribution
            - try { helm3 delete simplehelm-from-repo-$run_id --namespace $k8s_namespace } catch {}
            - jfrog rt curl -XDELETE "/api/build/${JFROG_CLI_BUILD_NAME}?buildNumbers=${JFROG_CLI_BUILD_NUMBER}&artifacts=1"
            - try { kubectl delete pod --namespace ${k8s_namespace} simplehelm-from-repo-$run_id-test-connection } catch {}
