resources:
  - name: S_SignReleaseBundle_5933_002_input_1
    type: ReleaseBundle
    configuration:
      sourceDistribution: s_distribution
      name: name
      version: '1'
  - name: S_SignReleaseBundle_5933_002_input_2
    type: ReleaseBundle
    configuration:
      sourceDistribution: s_distribution
      name: name
      version: '1'
  - name: S_SignReleaseBundle_5933_002_output
    type: ReleaseBundle
    configuration:
      sourceDistribution: s_distribution
      name: name
      version: '1'

pipelines:
  - name: SignReleaseBundle
    configuration:
      inputResources:
        - name: S_SignReleaseBundle_5933_002_input_1
    steps:
      - name: S_SignReleaseBundle_5933_002
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: S_SignReleaseBundle_5933_002_input_2
          outputResources:
            - name: S_SignReleaseBundle_5933_002_output
