pipelines:
  - name: Ps_variable_resolved_14856
    steps:
      - name: Ps_variable_resolved_14856
        type: Bash
        configuration:
          integrations:
            - name: exportWithKey14856
            - name: exportWithFormat14856
        execution:
          onExecute:
            - echo ${exportWithKey}
            - echo ${int_exportWithKey14856_exportWithKey}
            - echo ${int_exportWithFormat14856_exportWithFormat}

