template: true

resources:
  - name: S_GoPublishModule_0026_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

  - name: S_GoPublishModule_0026_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: GoPublishModule
    steps:
      - name: S_GoPublishModule_0026_1
        type: GoPublishModule
        configuration:
          inputResources:
            - name: S_GoPublishModule_0026_GitRepo
          outputResources:
            - name: S_GoPublishModule_0026_BuildInfo
          integrations:
            - name: s_artifactory
          version: "v0.26.${run_number}"
          targetRepository: test-automation-go-local
          autoPublishBuildInfo: true
          sourceLocation: "yaml/.jfrog-pipelines/"
      - name: S_GoPublishModule_0026_2
        type: Bash
        configuration:
          inputResources:
            - name: S_GoPublishModule_0026_BuildInfo
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - if [ "$res_S_GoPublishModule_0026_BuildInfo_buildName" != "$JFROG_CLI_BUILD_NAME" ]; then return 1; fi
            - if [ "$res_S_GoPublishModule_0026_BuildInfo_buildNumber" != "$JFROG_CLI_BUILD_NUMBER" ]; then return 1; fi
            - jfrog rt download --fail-no-op --insecure-tls=${no_verify_ssl} --limit=1 "test-automation-go-local/go.service/@v/v0.26.${run_number}.info"
            - jfrog rt curl -XDELETE "/api/build/${JFROG_CLI_BUILD_NAME}?buildNumbers=${JFROG_CLI_BUILD_NUMBER}&artifacts=1"
