template: true
valuesFilePath: ../values/gitRepoValues.yml

resources:
  - name: S_NpmBuild_8304_001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}
  - name: S_NpmBuild_8304_001_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: test-automation-generic-local/myFile

pipelines:
  - name: pipeline_S_NpmBuild_8304_001_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: S_NpmBuild_8304_001_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: S_NpmBuild_8304_001_GitRepo
          outputResources:
            -  name: S_NpmBuild_8304_001_FileSpec
        execution:
          onExecute:
            - cd $(find_resource_variable S_NpmBuild_8304_001_GitRepo resourcePath)/yaml/.jfrog-pipelines/npm
            - replace_envs package.json
            - jfrog rt upload package.json test-automation-generic-local/package.json
            - write_output S_NpmBuild_8304_001_FileSpec pattern="test-automation-generic-local/package.json"

      - name: S_NpmBuild_8304_001_2
        type: NpmBuild
        configuration:
          inputResources:
            - name: S_NpmBuild_8304_001_GitRepo
            - name: S_NpmBuild_8304_001_FileSpec
          integrations:
            - name: s_artifactory
          sourceLocation: "yaml/.jfrog-pipelines/npm"
          resolverRepo: test-automation-npm-remote
        execution:
          onStart:
            - pushd $(find_resource_variable $inputGitRepoResourceName resourcePath)/$(find_step_configuration_value sourceLocation)
            - rm package.json # removing the file to be replaced using the FileSpec
            - ls
            - popd
