template: true

resources:
  - name: S_GradleBuild_5680_0027_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}
  - name: S_GradleBuild_5680_0027_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: test-automation-generic-local/S_GradleBuild_5680_0027_Config


pipelines:
  - name: GradleBuild
    steps:
      - name: S_GradleBuild_5680_0027_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: S_GradleBuild_5680_0027_GitRepo
          outputResources:
            -  name: S_GradleBuild_5680_0027_FileSpec
        execution:
          onExecute:
            - cd $(find_resource_variable S_GradleBuild_5680_0027_GitRepo resourcePath)/tests/gradle
            - jfrog rt upload config test-automation-generic-local/S_GradleBuild_5680_0027_Config

      - name: S_GradleBuild_5680_0027_2
        type: GradleBuild
        configuration:
          inputResources:
            - name: S_GradleBuild_5680_0027_GitRepo
            - name: S_GradleBuild_5680_0027_FileSpec
          integrations:
            - name: s_artifactory
          sourceLocation: tests/gradle
          configFileName: S_GradleBuild_5680_0027_Config
          configFileLocation: .
          gradleCommand: hello
