resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: Ps_variable_resolved_67301
    steps:
      - name: Ps_variable_resolved_67301
        type: Bash
        configuration:
          integrations:
            - name: genericExportKey
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
          inputResources:
            - name: myFirstRepo
        execution:
          onExecute:
            - echo ${nonSecure}
            - echo ${secure}
            - echo {{.jfrog-pipelines.sourceRepository}}
            
            
