

resources:
  - name: S_DockerBuild
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

pipelines:
  - name: DockerBuild
    steps:
      - name: S_DockerBuild_5933_020
        type: DockerBuild
        configuration:
          dockerImageName: jfrog-pipelines-docker/linux
          dockerImageTag: "${run_id}"
          dockerFileLocation: "dockerfiles"
          inputResources:
            - name: S_DockerBuild
          integrations:
            - name: s_artifactory
        #execution:
          #onStart:
            #- artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')
            #- cd $res_S_DockerBuild_5933_020_GitRepo_resourcePath
            #- mkdir -p dockerfiles
            #- echo "FROM hello-world" > dockerfiles/Dockerfile
