resources:
  - name: P_WF_5933_001_resource
    type: PropertyBag
    configuration:
      test: test

pipelines:
  - name: pipeline_P_WF_5933_001
    configuration:
      integrations:
        - name: s_artifactory
    steps:
      - name: P_WF_5933_001_1
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_5933_001_resource
        execution:
          onExecute:
            - echo "executing step..."
      - name: P_WF_5933_001_2
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_5933_001_resource
          inputSteps:
            - name: P_WF_5933_001_1
        execution:
          onExecute:
            - echo "executing step..."
