resources:
  - name: S_Bash_0543_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/fileSpecBash/s_foo"
      limit: 1
      sortBy:
        - created

pipelines:
  - name: FileSpec
    steps:
      - name: S_Bash_0543
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0543_FileSpec
        execution:
          onExecute:
            - echo "executing step"
            - pushd $res_S_Bash_0543_FileSpec_resourcePath
            - if [ -f "./fileSpecBash/s_foo" ]; then echo "found the file"; fi
            - if [ ! -f "./fileSpecBash/s_foo" ]; then echo "error finding the file"; exit 1; fi
            - popd
