resources:
  - name: EXT_S_LX_AU_0002_remoteFile
    type: RemoteFile
    configuration:
      source: s_artifactory
      fileLocation: test-automation-generic-local
      fileName: EXT_S_LX_AU_0002_remoteFile.txt

pipelines:
  - name: RemoteFile
    steps:
      - name: EXT_S_LX_AU_0002_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            - name: EXT_S_LX_AU_0002_remoteFile
        execution:
          onExecute:
            - echo "${run_id}" > EXT_S_LX_AU_0002_remoteFile.txt
            - jfrog rt upload EXT_S_LX_AU_0002_remoteFile.txt test-automation-generic-local

      - name: EXT_S_LX_AU_0002_2
        type: UploadArtifact
        configuration:
          targetPath: test-automation-generic-local/EXT_S_LX_AU_0002.txt
          integrations:
            - name: s_artifactory
          inputResources:
            - name: EXT_S_LX_AU_0002_remoteFile

      - name: EXT_S_LX_AU_0002_3
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputSteps:
            - name: EXT_S_LX_AU_0002_2
        execution:
          onExecute:
            - jfrog rt download test-automation-generic-local/EXT_S_LX_AU_0002.txt EXT_S_LX_AU_0002.txt
            - contents=$(cat EXT_S_LX_AU_0002.txt)
            - if [ "$contents" != "$run_id" ]; then return 1; fi
