pipelines:

  - name: S_WF_030
    configuration:
      nodePool: win_2019
    steps:
  
      - name: S_WF_030_001
        type: PowerShell
        execution:
          onExecute:
            - Write-Output "Step 1 is running"
  
      - name: S_WF_030_002
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_030_001
        execution:
          onExecute:
            - Write-Output "Step 2 is running"
            - throw "intentionally failing the step"
  
      - name: S_WF_030_003
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_030_001
          affinityGroup: some_ag
        execution:
          onExecute:
            - Write-Output "Step 3 is running"
  
      - name: S_WF_030_004
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_030_002
            - name: S_WF_030_003
          affinityGroup: some_ag
        execution:
          onExecute:
            - Write-Output "I should not be running."
  
      - name: S_WF_030_005
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_030_004
          affinityGroup: some_ag
        execution:
          onExecute:
            - Write-Output "I should not be running too."
