

pipelines:
  - name: Ps_variable_resolved_67301
    steps:
      - name: Ps_variable_resolved_67301
        type: Bash
        configuration:
          integrations:
            - name: genericExportKey
            - name: s_artifactory
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
          
        execution:
          onExecute:
            #- echo ${int_genericExportKey_secure}
            - echo ${int_s_artifactory_user}
            #- echo ${secure}
            - echo {{.jfrog-pipelines.sourceRepository}}
            
            
