

template: true


resources:
  - name: S_NpmPublish
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: pipeline_S_NpmPublish
    steps:
      - name: S_NpmPublish_5933_007_1
        type: Bash
        configuration:
          inputResources:
            - name: S_NpmPublish
          integrations:
            - name: s_artifactory1
        execution:
          onStart:
            - replace_envs ${res_S_NpmPublish_5933_007_GitRepo_resourcePath}/tests/npm/package.json
          onExecute:
            - jfrog npm-config --repo-resolve 'test-automation-npm-remote' --server-id-resolve s_artifactory1
            - jfrog npm install --quiet
      
