
resources:
  - name: S_DockerBuild_5933_001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

pipelines:
  - name: DockerBuild
    steps:
      - name: S_DockerBuild_5933_001_1
        type: DockerBuild
        configuration:
          dockerImageName: https://b155902.jfrog-pipelines.com/artifactory/jfrog-pipelines-docker
          dockerImageTag: "${run_id}"
          inputResources:
            - name: S_DockerBuild_5933_001_GitRepo
          integrations:
            - name: s_artifactory
