pipelines:
  - name: pipelines_I_Jenkins_0019
    steps:
      - name: I_Jenkins_0019
        type: Jenkins
        configuration:
          jenkinsJobName: var-pipeline-proj    # Jenkins job/pipeline name. required
          priority: 2
          buildParameters:
            key1: 1
            key2: 2
          integrations:
            - name: i_testJenkins   # required Jenkins integration
        
      - name: branch_environment_operate
        type: Jenkins
        configuration:
          inputSteps:
            - name: I_Jenkins_0019
              status:
                - error
                - skipped
          integrations:
            - name: i_testJenkins
          jenkinsJobName: tools/platform/environment_operate
          buildParameters:
            SERVER_NAME: ${res_environmentOperateBag_serverName}
            EXPIRY: "3d"
            ACTION: "upgrade"

