pipelines:
  
  - name: S_WF_024
    configuration:
      #nodePool: oneboxMacOS135
      nodePool: u18dynamic
      affinityGroup: some_ag
    steps:
  
      - name: S_WF_024_001
        type: Bash
        configuration:
          #nodePool: oneboxMacOS134
          nodePool: u18dynamic
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "Step 1 is running"
  
      - name: S_WF_024_002
        type: Bash
        configuration:
          affinityGroup: some_ag
          #nodePool: oneboxMacOS135
          nodePool: u18dynamic
          inputSteps:
            - name: S_WF_024_001
          
        execution:
          onStart:
            - add_run_variables step_2_var="step2"
          onExecute:
            - echo "Step 2 is running"
  
