template: true
valuesFilePath: ../values/gitRepoValues.yml

resources:
  - name: S_PS_HelmDeploy_BuildInfo_8309_003
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: helmbuild
      buildNumber: 1

  - name: S_PS_HelmDeploy_GitRepo_8309_003
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: master

pipelines:
  - name: S_PS_HelmDeploy_8309_003
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          release_name_generic: "simplehelm-generic"
          k8s_namespace: "pipe-master-pool"
      nodePool: win_2019

    steps:
      - name: S_PS_HelmDeploy_8309_003_create_build
        type: PowerShell
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: S_PS_HelmDeploy_GitRepo_8309_003
          outputResources:
            - name: S_PS_HelmDeploy_BuildInfo_8309_003
        execution:
          onExecute:
            - add_run_variables JFROG_CLI_BUILD_NUMBER=${run_id}
            - Push-Location $res_S_PS_HelmDeploy_GitRepo_8309_003_resourcePath/tests/core/helmdeploy
            - jfrog rt u simplehelm/ "helmgeneric/S_PS_HelmDeploy_8309_003/" --flat=false --build-name=$JFROG_CLI_BUILD_NAME --build-number=${JFROG_CLI_BUILD_NUMBER}
            - jfrog rt bce ${JFROG_CLI_BUILD_NAME} ${JFROG_CLI_BUILD_NUMBER}
            - jfrog rt bp ${JFROG_CLI_BUILD_NAME} ${JFROG_CLI_BUILD_NUMBER}
            - write_output S_PS_HelmDeploy_BuildInfo_8309_003 buildName=${JFROG_CLI_BUILD_NAME} buildNumber=${JFROG_CLI_BUILD_NUMBER}

      - name: deploy_helm_chart_from_generic_repo
        type: HelmDeploy
        configuration:
          inputSteps:
            - name: S_PS_HelmDeploy_8309_003_create_build
          integrations:
            - name: s_artifactory
            - name: s_kubernetes
          inputResources:
            - name: S_PS_HelmDeploy_BuildInfo_8309_003
          helmVersion: 3
          releaseName: ${release_name_generic}
          chartPath: S_PS_HelmDeploy_8309_003/simplehelm/
          flags: "--force --wait --timeout 900s --set image.repository=trriplejay/simplehelm --set image.tag=latest"
          valueFilePaths:
            - values.yaml
          lint: true
          lintFlags: "--strict"
          test: true
        execution:
          onComplete:
            - helm3 delete simplehelm-generic-$run_id --namespace $k8s_namespace
            - jfrog rt curl -XDELETE "/api/build/${JFROG_CLI_BUILD_NAME}?buildNumbers=${run_id}&artifacts=1"
            - kubectl delete pod --namespace ${k8s_namespace} simplehelm-generic-$run_id-test-connection
