

resources:
  - name: S_PS_GPM_8305_004_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

pipelines:
  - name: pipeline_S_PS_GoPublishModule_8305_004
    configuration:
      nodePool: win_2019
      jfrogCliVersion: 2
    steps:
      - name: S_PS_GoPublishModule_8305_004
        type: GoPublishModule
        configuration:
          environmentVariables:
            target_repository: "test-automation-go-local"
          inputResources:
            - name: S_PS_GPM_8305_004_GitRepo
          integrations:
            - name: s_artifactory
          version: "v1.83054.${run_number}"
          targetRepository: "${target_repository}"
          sourceLocation: "yaml/.jfrog-pipelines/Go"
