
resources:
  - name: S_DockerBuild_5933_015_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

  - name: S_DockerBuild_5933_015_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory1
      pattern: test-automation-generic-local/DockerBuild_5933_015_Dockerfile

pipelines:
  - name: S_DockerBuild
    steps:
      - name: S_DockerBuild_5933_015_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            -  name: S_DockerBuild_5933_015_FileSpec
        execution:
          onExecute:
            - artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')
            - echo "FROM $artifactory_registry_url/test-automation-docker-remote/hello-world" > Dockerfile
            - jfrog rt upload Dockerfile test-automation-generic-local/DockerBuild_5933_015_Dockerfile

      - name: S_DockerBuild_5933_015_2
        type: DockerBuild
        configuration:
          inputSteps:
            - name: S_DockerBuild_5933_015_1
          affinityGroup: S_DockerBuild_5933_015
          dockerImageName: b155902.jfrog-pipelines.com/test-automation-docker-local
          dockerImageTag: "${run_id}"
          dockerFileName: yaml/.jfrog-pipelines/Dockerfile

          inputResources:
            - name: S_DockerBuild_5933_015_GitRepo
            - name: S_DockerBuild_5933_015_FileSpec
          integrations:
            - name: s_artifactory
            - name: s_rt_dockerRegistry
        execution:
          onStart:
            - artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')
          onComplete:
            - docker rmi "${artifactory_registry_url}/test-automation-docker-local/s_dockerbuild_5933:${run_id}" || true

      - name: S_DockerPush_5849_001_2
        type: DockerPush
        configuration:
          affinityGroup: S_DockerBuild_5933_015
          targetRepository: test-automation-docker-local
          inputSteps:
            - name: S_DockerPush_5849_001_1
          integrations:
            - name: s_artifactory
