

resources:
  - name: S_PS_MvnBuild_8306_005_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

pipelines:
  - name: pipeline_S_PS_MvnBuild_8306_005
    configuration:
      nodePool: win_2019
      jfrogCliVersion: 2
    steps:
      - name: S_PS_MvnBuild_8306_005
        type: MvnBuild
        configuration:
          environmentVariables:
            source_location: "tests/mvn"
          inputResources:
            - name: S_PS_MvnBuild_8306_005_GitRepo
          integrations:
            - name: s_artifactory
          sourceLocation: "${source_location}"
          configFileName: config
          configFileLocation: .
