template: true

resources:
  - name: S_GoBuild_0001_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: master

pipelines:
  - name: goBuild
    steps:
      - name: S_GoBuild_0001
        type: GoBuild
        configuration:
          inputResources:
            - name: S_GoBuild_0001_GitRepo
          integrations:
            - name: s_artifactory
