resources:
  - name: S_XrayScan_0001_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: 'name'
      buildNumber: '1'

pipelines:
  - name: XrayScan
    steps:
      - name: S_XrayScan_0001
        type: XrayScan
        configuration:
          inputResources:
            - name: S_XrayScan_0001_BuildInfo
              newVersionOnly: true
