resources:
  - name: myFirstRepo11
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: Ps_variable_resolved_673011
    steps:
      - name: Ps_variable_resolved_673011
        type: Bash
        configuration:
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
          inputResources:
            - name: myFirstRepo11
        execution:
          onExecute:
            - echo {{gitBranch}}
            - echo {{.jfrog-pipelines.sourceRepository}}
            - echo 'test1222'
            - echo 'test1222x'
      
