pipelines:
  - name: Ps_variable_resolved_14856
    steps:
      - name: Ps_variable_resolved_14856
        type: Bash
        configuration:
          integrations:
            - name: exportWithKey14856
            - name: exportWithFormat14856
        execution:
          onExecute:
            - withkey=${exportWithKey}
            - echo $withkey
            - if [ "$withkey" != "exportWithKeyq" ]; then return 1; fi 
            - if [ "${int_exportWithKey14856_exportWithKey}" != exportWithKey ]; then return 1; fi 
            - if [ "${int_exportWithFormat14856_exportWithFormat}" != exportWithFormat ]; then return 1; fi 
            - if [ "${exportWithFormat}" != "" ]; then return 1; fi 
            
