resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: Ps_variable_resolved_6730
    steps:
      
