resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: test.*
      buildOn:
        commit: true  

pipelines:
  - name: Ps_variable_resolved_67301
    steps:
      - name: Ps_variable_resolved_67301
        type: Bash
        configuration:
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
          inputResources:
            - name: myFirstRepo
        execution:
          onExecute:
            - echo {{gitBranch}} + 'tests'
            - echo {{.jfrog-pipelines.sourceRepository}}
            
            
