template: true

resources:
  - name: S_HelmPublish_5849_002_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}
  - name: S_HelmPublish_5849_002_HelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: s_artifactory
      repository: test-automation-helm-local
      version: version
      chart: chart
  - name: S_HelmPublish_5849_002_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: HelmPublish
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NUMBER: ${run_id}
          CHART_VERSION: v0.5849002.${run_id}
    steps:
      - name: S_HelmPublish_5849_002_1
        type: HelmPublish
        configuration:
          chartPath: "./tests/helmCharts/myChart"
          flags: "--version ${CHART_VERSION}"
          autoPublishBuildInfo: true
          inputResources:
            - name: S_HelmPublish_5849_002_GitRepo
          outputResources:
            - name: S_HelmPublish_5849_002_BuildInfo
            - name: S_HelmPublish_5849_002_HelmChart
          integrations:
            - name: s_artifactory
        execution:
          onStart:
            - replace_envs ${res_S_HelmPublish_5849_002_GitRepo_resourcePath}/tests/helmCharts/myChart/Chart.yaml

      - name: S_HelmPublish_5849_002_2
        type: Bash
        configuration:
          inputSteps:
            - name: S_HelmPublish_5849_002_1
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - buildInfoFilePath=$(jfrog rt search "*/${JFROG_CLI_BUILD_NAME}/${run_id}*.json" | jq -r '.[0].path')
            - buildInfoFileData=$(jfrog rt curl -XGET /api/storage/${buildInfoFilePath})
            - artifactSha=$(echo $buildInfoFileData | jq -r '.checksums.sha256')
            - if [ -z "${project_key}" ]; then project="default"; else project="${project_key}"; fi
            - artifactPath="${project}/${JFROG_CLI_BUILD_NAME}/${run_id}"
            - "stepArtifact=$(curl -sS -H \"Authorization: Bearer $builder_api_token\" -H 'Content-Type: application/json' \"${pipelines_api_url}/stepArtifacts?artifactPath=${artifactPath}&artifactSha=${artifactSha}&artifactType=buildInfo\")"
            - jfrog rt curl -XDELETE "/api/build/${JFROG_CLI_BUILD_NAME}?buildNumbers=${run_id}&artifacts=1"
            - stepArtifactSha=$(echo $stepArtifact | jq -r '.artifactSha')
            - if [ "$stepArtifactSha" != "$artifactSha" ]; then return 1; fi
