resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: Ps_variable_resolved_6730
    steps:
      - name: Ps_variable_resolved_6730
        type: Bash
        configuration:
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
        execution:
          onExecute:
            - echo {{gitBranch}}
            - echo {{.jfrog-pipelines.sourceRepository}}
            - cd 'test1'
            
