resources:
  - name: S_CreateReleaseBundle_0006_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: 'name'
      buildNumber: '1'
  - name: S_CreateReleaseBundle_0006_ReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: s_distribution
      name: name
      version: '1'

pipelines:
  - name: pipeline_S_CreateReleaseBundle_0006
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NUMBER: "${run_id}"
    steps:
      - name: S_CreateReleaseBundle_0006_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            - name: S_CreateReleaseBundle_0006_BuildInfo
        execution:
          onExecute:
            - echo "${run_id}" > S_CreateReleaseBundle_0006.txt
            - jfrog rt upload S_CreateReleaseBundle_0006.txt test-automation-generic-local
            - jfrog rt build-publish ${JFROG_CLI_BUILD_NAME} ${JFROG_CLI_BUILD_NUMBER}
            - write_output S_CreateReleaseBundle_0006_BuildInfo buildName=${JFROG_CLI_BUILD_NAME} buildNumber=${JFROG_CLI_BUILD_NUMBER}
      - name: S_CreateReleaseBundle_0006_2
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: ${JFROG_CLI_BUILD_NAME}
          releaseBundleVersion: ${run_id}
          dryRun: false
          inputResources:
            - name: S_CreateReleaseBundle_0006_BuildInfo
          outputResources:
            - name: S_CreateReleaseBundle_0006_ReleaseBundle
      - name: S_CreateReleaseBundle_0006_3
        type: Bash
        configuration:
          inputResources:
            - name: S_CreateReleaseBundle_0006_ReleaseBundle
        execution:
          onExecute:
            - echo "Deleting distribution..."
            - distributionUrl="$res_S_CreateReleaseBundle_0006_ReleaseBundle_sourceDistribution_url"
            - releaseBundleName=$(find_resource_variable S_CreateReleaseBundle_0006_ReleaseBundle name)
            - releaseBundleVersion=$(find_resource_variable S_CreateReleaseBundle_0006_ReleaseBundle version)
            - jfrog config add distribution --overwrite --insecure-tls=$no_verify_ssl --dist-url $distributionUrl --user $res_S_CreateReleaseBundle_0006_ReleaseBundle_sourceDistribution_user --apikey $res_S_CreateReleaseBundle_0006_ReleaseBundle_sourceDistribution_apikey --interactive=false
            - jfrog config use distribution
            - jfrog rt release-bundle-delete --delete-from-dist=true --insecure-tls=$no_verify_ssl $releaseBundleName $releaseBundleVersion
            - jfrog config remove distribution
            - echo "Checking resource..."
            - if [ "$res_S_CreateReleaseBundle_0006_ReleaseBundle_name" != "${JFROG_CLI_BUILD_NAME}" ]; then return 1; fi
            - if [ "$res_S_CreateReleaseBundle_0006_ReleaseBundle_version" != "${run_id}" ]; then return 1; fi
            - if [ "$res_S_CreateReleaseBundle_0006_ReleaseBundle_isSigned" == "true" ]; then return 1; fi
