resources:
  - name: syncEnv
    type: GitRepo
    configuration:
      gitProvider: gitHub
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: {{gitBranch}}

pipelines:
  - name: syncEnv
    configuration:
      integrations:
        - name: s_gitHub
    steps:
      - name: syncEnv
        type: Bash
        configuration:
          
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
          inputResources:
            - name: syncEnv
        execution:
          onExecute:
            - echo {{gitBranch}}
            - echo {{.jfrog-pipelines.sourceRepository}}
            - echo 'test1222'
            - echo 'test1222x'
      
