
pipelines:
  - name: S_WF_8033_06_pipe
    steps:
      - name: S_WF_8033_06_step
        type: TriggerPipeline
        configuration:
          integrations:
            - name: trigger_platformToken
          pipelineName: go_app
         # stepName: test_docker_build

  - name: S_WF_8033_06_target
    steps:
      - name: S_WF_8033_06_target_step
        type: Bash
        execution:
          onExecute:
            - echo "Hello world"
