template: true

resources:
  - name: S_MvnBuild_5680_0034_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

pipelines:
  - name: MvnBuild
    steps:
      - name: S_MvnBuild_5680_0034_1
        type: MvnBuild
        configuration:
          environmentVariables:
            my_command: "'clean test'"
          inputResources:
            - name: S_MvnBuild_5680_0034_GitRepo
          integrations:
            - name: s_artifactory
          sourceLocation: "tests/mvn"
          mvnCommand: "${my_command}"
          resolverSnapshotRepo: test-automation-mvn-remote
          resolverReleaseRepo: test-automation-mvn-remote
          deployerSnapshotRepo: test-automation-mvn-local
          deployerReleaseRepo: test-automation-mvn-local
        execution:
          onSuccess:
            - pushd $(find_resource_variable $inputGitRepoResourceName resourcePath)/tests/mvn
            - if [ -f "target/maventest-2.17-SNAPSHOT.jar" ]; then echo "TEST FAILED"; return 1; fi
            - if [ ! -f "target/surefire-reports/TEST-artifactory.test.AppTest.xml" ]; then echo "TEST FAILED"; return 1; fi
            - add_run_variables TEST_SUCCESS=true
      - name: S_MvnBuild_5680_0034_2
        type: Bash
        configuration:
          inputSteps:
            - name: S_MvnBuild_5680_0034_1
        execution:
          onExecute:
            - if [ "$TEST_SUCCESS" != "true" ]; then return 1; fi
