resources:
  - name: EXT_S_LX_AU_0007_fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/EXT_S_LX_AU_0007_fileSpec.txt"

pipelines:
  - name: UploadArtifact
    steps:
      - name: EXT_S_LX_AU_0007_1
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            - name: EXT_S_LX_AU_0007_fileSpec
        execution:
          onExecute:
            - echo "${run_id}" > EXT_S_LX_AU_0007_fileSpec.txt
            - jfrog rt upload EXT_S_LX_AU_0007_fileSpec.txt test-automation-generic-local

      - name: EXT_S_LX_AU_0007_2
        type: UploadArtifact
        configuration:
          targetPath: test-automation-generic-local/EXT_S_LX_AU_0007.txt
          properties: propertyOne=1;propertyTwo=1,2,3
          integrations:
            - name: s_artifactory
          inputResources:
            - name: EXT_S_LX_AU_0007_fileSpec

      - name: EXT_S_LX_AU_0007_3
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputSteps:
            - name: EXT_S_LX_AU_0007_2
        execution:
          onExecute:
            - jfrog rt download --props "propertyOne=1;pipelines_run_number=${run_number}" test-automation-generic-local/EXT_S_LX_AU_0007.txt EXT_S_LX_AU_0007.txt
            - contents=$(cat EXT_S_LX_AU_0007.txt)
            - if [ "$contents" != "${run_id}" ]; then return 1; fi
