resources:
  - name: P_WF_5933_012_resource
    type: PropertyBag
    configuration:
      test: test

pipelines:
  - name: PropertyBag
    configuration:
      integrations:
        - name: s_artifactory
    steps:
      - name: P_WF_5933_012_1
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_5933_012_resource
        execution:
          onExecute:
            - echo "executing step..."
      - name: P_WF_5933_012_2
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_5933_012_resource
          inputSteps:
            - name: P_WF_5933_012_1
        execution:
          onExecute:
            - echo "executing step..."
