

pipelines:
  - name: Ps_variable_resolved_67301
    steps:
      - name: Ps_variable_resolved_67301
        type: Bash
        configuration:
          integrations:
            - name: genericNew1
            - name: s_artifactory
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
          
        execution:
          onExecute:
            - echo ${int_genericNew1_data}
            - echo ${int_s_artifactory_user}
            - echo ${data}
            - echo {{.jfrog-pipelines.sourceRepository}}
            
            
