
resources:
  - name: S_PS_GradleBuild_5680_0033_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

pipelines:
  - name: pipeline_S_PS_GradleBuild_5680_0033
    configuration:
      nodePool: win_2019
    steps:
      - name: S_PS_GradleBuild_5680_0033_1
        type: GradleBuild
        configuration:
          inputResources:
            - name: S_PS_GradleBuild_5680_0033_GitRepo
          integrations:
            - name: s_artifactory
          usesPlugin: true
          resolverRepo: test-automation-gradle-remote
          deployerRepo: test-automation-gradle-local
          sourceLocation: "tests/gradle"
          gradleCommand: "hello"
        execution:
          onStart:
            - add_run_variables JFROG_CLI_BUILD_NUMBER=${run_id}
          onSuccess:
            - |
              $ymlPath = Join-Path ( find_resource_variable $inputGitRepoResourceName resourcePath ) ( Join-Path ( find_step_configuration_value sourceLocation ) ".jfrog/projects/gradle.yaml" )
              $plugin = Select-String -Path $ymlPath -Pattern "usePlugin: true" -Quiet
              echo "$plugin"
              if ( -not $plugin) { throw "TEST FAILED" }
              add_run_variables TEST_SUCCESS=true
      - name: S_PS_GradleBuild_5680_0033_2
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_PS_GradleBuild_5680_0033_1
        execution:
          onExecute:
            - if ( "$TEST_SUCCESS" -ne "true" ) { throw "Test failed"}
