
resources:
  - name: S_DockerBuild_5933_015_GitRepo_Xray
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: nitind123/newTemplates
      branches:
        include: {{gitBranch}}

  - name: S_DockerBuild_5933_015_FileSpec_Xray
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: test-automation-generic-local/DockerBuild_5933_015_Dockerfile

  - name: S_DockerBuild_0009_output_Xray
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: name
      buildNumber: '1'

pipelines:
  - name: S_DockerBuild_Xray
    configuration:
      nodePool: win_2019
    steps:
      - name: S_DockerBuild_5933_015_1_Xray
        type: PowerShell
        configuration:
          integrations:
            - name: s_artifactory
          outputResources:
            -  name: S_DockerBuild_5933_015_FileSpec_Xray
        execution:
          onExecute:
            - artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')
            - echo "FROM $artifactory_registry_url/test-automation-docker-remote/hello-world" > Dockerfile
            - jfrog rt upload Dockerfile test-automation-generic-local/DockerBuild_5933_015_Dockerfile

      - name: S_DockerBuild_5933_015_2_Xray
        type: DockerBuild
        configuration:
          inputSteps:
            - name: S_DockerBuild_5933_015_1_Xray
          affinityGroup: S_DockerBuild_5933_015
          dockerImageName: jpd587702896.jfrogdev.org/test-automation-docker-local/image
          dockerImageTag: "${run_id}"
          dockerFileName: yaml/.jfrog-pipelines/Dockerfile

          inputResources:
            - name: S_DockerBuild_5933_015_GitRepo_Xray
            - name: S_DockerBuild_5933_015_FileSpec_Xray
          integrations:
            - name: s_artifactory
            - name: s_rt_dockerRegistry
        execution:
          onStart:
            - artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')
          onComplete:
            - docker rmi "${artifactory_registry_url}/test-automation-docker-local/s_dockerbuild_5933:${run_id}" || true

      - name: S_DockerPush_5849_001_2_Xray
        type: DockerPush
        configuration:
          affinityGroup: S_DockerBuild_5933_015
          targetRepository: test-automation-docker-local
          autoPublishBuildInfo: true
          inputSteps:
            - name: S_DockerBuild_5933_015_2_Xray
          integrations:
            - name: s_artifactory
          outputResources:
            - name: S_DockerBuild_0009_output_Xray

      - name: docker_scan_Xray
        type: XrayScan
        configuration:
          inputResources:
            - name: S_DockerBuild_0009_output_Xray
