Pipeline:
  name: foo

GitRepo:
  name: fooGitRepo
  gitProvider: s_gitHub
  path: nitind123/newTemplates
  branches:
    include: master

artifactoryIntegration: s_artifactory

Image:
  name: fooImage
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: foobuild
  dockerImageName: foo
  dockerFileName: foo
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

DockerPush:
  name: foopush
  targetRepository: foo

BuildInfo:
  autoPublishBuildInfo: true
  name: fooBuildInfo
