GitHub:
  Org_test_Automation:
    path: nitind123/newTemplates
  Org_test_Automation_bash:
    path: nitind123/newTemplates
  Org_test_Automation_PowerShell:
    path: nitind123/Org_test_Automation_PowerShell
  templates:
    path: nitind123/templates
  Org_test_Automation_Webhooks:
      path: nitind123/Org_test_Automation_Webhooks

GitHubEnterprise:
  Org_test_Automation:
    path: PIPA/Org_test_Automation
  test_automation:
    path: jfbeta/test_automation
  test:
    path: shiptest/test

GitLab:
  test_automation:
    path: jfbeta/test_automation
  jfrogtesting:
    path: jfbeta/jfrogtesting
  templates:
    path: jfbeta/templates

BitbucketCloud:
  jfrogtesting:
    path: jfbeta/jfrogtesting
  test_automation:
    path: jfbeta/test_automation
  org_test_automation:
    path: PIPA/org_test_automation
  templates:
    path: PIPA/templates

BitbucketServer:
  automation:
    path: PIP/automation
  test_automation:
    path: PIP/test_automation
  test:
    path: ~ranjanks/test
  templates:
    path: PIP/templates

Projects:
  FirstProjectKey: first
  SecondProjectKey: second
