metadata:

  serviceName:  nodeJsTemplate

  node: "18"

inputs:
  pipeline:
    configuration:
      integrations:
        - s_gitHub
        - s_slack
      environmentVariables:
        foo: bar
        test: env
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10

  sourceRepository:
    path: nitind123/newTemplates
    gitProvider: s_gitHub
    branches:
      include: nodejsTemplate

  integrations:

    artifactory: s_artifactory
    sonar: s_sonar

configurations:

  sourceDirectory: ''

  steps:

    codeQuality:

      commands:
        - npm run lint:api


    sonarScan:

      commands:
        - npm run build


    build:

      commands:
        - npm run build


    publish:

      commands:
        - jfrog rt publish


    clamScan:

      commands:
        - npm run build
        

controls:

  enableQuality: true
  isPublishAvailable: true

  triggerBy:
    sourceRepository: true
