metadata:
  serviceName:  nodejsTemplate
  node: "18"

inputs:
  pipeline:
    configuration:
      integrations:
        - s_gitHub
        - s_slack
      environmentVariables:
        foo: bar
        test: env
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10

  sourceRepository:
    path: nitind123/newTemplates
    gitProvider: s_gitHub
    branches:
      include: master

  integrations:
    artifactory: s_gitHub
    sonar: s_sonar

configurations:

  sourceDirectory: 'yaml/javaTem'

  steps:
    build:
      onStart:
        - on_start
      onExecute:
        - npm run build
      onFailure:
        - send_notification
      onSuccess:
        - send_notification

    codeQuality:
      onStart:
        - npm run build
      onExecute:
        - npm run lint:api
      onFailure:
        - send_notification
      onSuccess:
        - send_notification


    sonarScan:
      onStart:
        - npm run build
      onExecute:
        - on_execute
      onFailure:
        - send_notification
      onSuccess:
        - send_notification

    publish:
      onExecute:
        - jfrog rt publish
      onFailure:
        - send_notification
      onSuccess:
        - send_notification


    clamScan:
      onStart:
        - npm run build
      onExecute:
        - on_execute
      onFailure:
        - send_notification
      onSuccess:
        - send_notification
        
controls:

  enableQuality: true
  enablePublish: true

  triggerBy:
    sourceRepository: true
