template:
  version: 0.0.0
  development: true

pipelines:
  - name: {{ .Values.Pipeline.name | default "Pipeline_10545" }}
    steps:
      - name: {{ .Values.Pipeline.name }}
        type: Bash
        configuration:
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
        execution:
          onExecute:
            - echo  {{ .Values.Pipeline.name }}