resources:
  - name: PS_Sync_9756_res
    type: GITRepo
    configuration:
      path: {{.jfrog-pipelines.sourceRepository}}
      gitProvider: goithub
      branches:
        include: {{gitBranch}}
      recurseSubmodules: true

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: PS_Sync_9756
    configuration:
      integrations:
        - name: goithub
    steps:
      - name: PS_Sync_9756
        type: Bash
        configuration:
          inputResources:
            - name: PS_Sync_9756_res
          outputResources:
            - name: propertyBag
          integrations:
            - name: goithub
        execution:
          onExecute:
            - pushd $res_PS_Sync_9756_res_resourcePath
            - ls
            - |
              if ls | grep -q 'NpmCI'; then
                echo "matched"
              fi
