

pipelines:
  - name: myPipeline_12191
    steps:
      - name: myPipeline_121911
        type: Bash
        configuration:
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
        execution:
          onExecute:
            - printenv
            - echo $JFROG_PIPELINES_API_URL
            - echo "first_step_nats"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
            - jfrog config add jftest-$step_id --url https://f119126.jfrog-pipelines.com --access-token ${JFROG_LOCAL_ARTIFACTORY_TOKEN}
            - touch test.txt
            - echo "hello" > test.txt
            - jfrog rt upload test.txt native-pipe-info/test.txt --server-id jftest-$step_id
      - name: myPipeline_12191
        type: Bash   
        configuration:
          inputSteps:
            - name: myPipeline_121911
        execution:
          onExecute:
            - echo "second_step_nats"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
            - echo env
