resources:
  - name: myRepo_native
    type: GITRepo
    configuration:
      path: nitind123/newTemplates
      gitProvider: s_gitHub
      branches:
        include: master

pipelines:
  - name: myPipeline_native
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
          environmentVariables:
            FORCE_RUN: 'true'
            admin_token: ''
        execution:
          onExecute:
           - ls
           
           - jfrog config add jftest --url https://f11912.jfrog-pipelines.com --access-token ${JFROG_LOCAL_ARTIFACTORY_TOKEN}
           
           #- jfrog rt dl example-repo-local --server-id https://f11912.jfrog-pipelines.com --url https://f11912.jfrog-pipelines.com --flat
           - jfrog rt upload steplet.json native-pipe-info?projectKey=native --server-id jftest
         #  - jfrog config add jftest --url https://f11912.jfrog-pipelines.com --access-token ${admin_token}
         #  - jfrog rt upload steplet.json test-automation-docker-local/ --server-id jftest
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "second_step"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
