resources:
  - name: signed_git
    type: GitRepo
    configuration:
      gitProvider: github_nitin
      path: nitind123/newTemplates
      branches:
        include: {{ gitBranch }}
  - name: signed_buildinfo_1
    type: BuildInfo
    configuration:
      sourceArtifactory: int_default_artifactory
 
pipelines:
  - name: test_signed_start_1
    steps:
      - name: create_info
        type: Bash
        configuration:
          inputResources:
            - name: signed_git
          integrations:
            - name: int_default_artifactory
          outputResources:
            - name: signed_buildinfo_1
        execution:
          onExecute:
            - cd $res_signed_git_resourcePath
            - touch server.js
            - jfrog rt upload server.js km-generic-local
            - jfrog rt build-publish --detailed-summary $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER > summaryOutput.json
            - save_artifact_info 'buildInfo' './summaryOutput.json' --build-name $JFROG_CLI_BUILD_NAME --build-number $JFROG_CLI_BUILD_NUMBER
      - name: print_info
        type: Bash
        configuration:
          inputSteps:
            - name: create_info
        execution:
          onExecute:
            - validate_artifact buildInfo --build-name $JFROG_CLI_BUILD_NAME --build-number $JFROG_CLI_BUILD_NUMBER
        
  - name: test_signed_stop_1
    steps:
      - name: validate_info
        type: Bash
        configuration:
          inputResources:
            - name: signed_buildinfo_1
        execution:
          onExecute:
            # - response=$(validate_artifact buildInfo --build-name ${res_signed_buildinfo_1_buildName} --build-number ${res_signed_buildinfo_1_buildNumber})
            - validate_artifact 'buildInfo' --build-name 'test_signed_start_1' --build-number 4
            - response=$(validate_artifact 'buildInfo' --build-name test_signed_start_1 --build-number 4)
            - echo $response
            - validateResult=$(echo "$response" | jq '.result')
            - if [ "$validateResult" != "true" ]; then echo "failed validation" && exit 1; fi
