

pipelines:
  - name: myPipeline_12191
    steps:
      - name: myPipeline_121911
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_LOG_LEVEL: DEBUG
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
        execution:
          onExecute:
            - url=`echo $JFROG_PIPELINES_API_URL | sed 's/\/v1//g'`
            - echo $url
            - echo "first_step_nats"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
            - jfrog config add jftest-$step_id --url $url --access-token ${JFROG_LOCAL_ARTIFACTORY_TOKEN}
            - touch test.txt
            - echo "hello" > test.txt
            - echo jfrog config show
            - jfrog rt upload test.txt native-pipe-info/test.txt --server-id jftest-$step_id
      - name: myPipeline_12191
        type: Bash   
        configuration:
          inputSteps:
            - name: myPipeline_121911
        execution:
          onExecute:
            - echo "second_step_nats"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
            - echo env
