resources:
  - name: EXT_S_SYC_AU_0012_fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local/test.txt"
pipelines:
  - name: EXT_S_SYC_AU_0012
    steps:
      - name: EXT_S_SYC_AU_0012
        type: UploadArtifact
        configuration:
          targetPath: "test-automation-generic-local/EXT_S_SYC_AU_0012"
          regExp: true
          integrations:
            - name: s_artifactory
          inputResources:
            - name: EXT_S_SYC_AU_0012_fileSpec
