
pipelines:
  - name: Nitin
    steps:
      - name: EXT_S_SYC_AU_0012
        type: UploadArtifact
        configuration:
          targetPath: "test-automation-generic-local/EXT_S_SYC_AU_0012"
          regExp: true
          integrations:
            - name: s_artifactory
          
