pipelines:
  - name: P_PS_10509_UploadArtifact_001
    steps:
      - name: P_PS_10509_UploadArtifact_001
        type: Bash
        configuration:
          environmentVariables:
            FORCE_RUN: 'true'
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
        execution:
          onExecute:
            - ls
            - jfrog rt upload steplet.json native-pipe-info/steplet.json?projectKey=native
