
# pipelines:
#   - name: P_files
#     steps:
#       - name: S_files
#         type: Bash
#         configuration:
#           environmentVariables:
#             env1: gitBranch
#             env2: sourceRepository
#         execution:
#           onExecute:
#             - echo test
resources:
  - name: myRepo_2
    type: GITRepo
    configuration:
      path: nitind123/newTemplates
      gitProvider: s_gitHub
pipelines:
  - name: P_files
    steps:
      - name: S_files
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: sourceRepository
        execution:
          onExecute:
            - echo test
