valuesFilePath: ./values/helm/values.yml

pipelines:
#  {{- with .Values.repoBranch }}
#   - name: P_flow
#     steps:
#       - name: S_flow
#         type: Bash
#         configuration:
#           environmentVariables:
#             env1: gitBranch
#         execution:
#           onExecute:
#             - echo {{ sha256sum "Hello world!" }}
#   {{ end }}
{{- define .Values.repoBranch }}
  - name: P_flow
    steps:
      - name: S_flow
        type: Bash
        configuration:
          environmentVariables:
            env1: gitBranch
            env2: {{  buildCustomCert "base64-encoded-ca-crt" "base64-encoded-ca-key" }}
            env3: {{ genCA "foo-ca" 365 }}
        execution:
          onExecute:
            - echo {{ sha256sum .Values.repoBranch }}
  {{ end }}
