resources:
  - name: pipeline_trigger_10509
    type: Artifact
    configuration:
      jfrogPlatformProvider: jfrogAccessToken_10509
      repositories:
        - example-repo-local
      artifactPath:
        include:
          - tools/*
        exclude:
          - exclude/*
      buildOn:
        deployed: true
        cached: true
        deleted: true
        copied: false
        moved: false
      branches:
        include: test
        exclude: master
pipelines:
  - name: PS_SYNC_10509_001
    steps:
      - name: PS_001
        type: Bash
        configuration:
          inputResources:
            - name: pipeline_trigger_10509
        execution:
          onExecute:
            - echo "test" 
