resources:
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.gitIntegration }}
      branches:
        include: {{ .Values.repo.branchPattern | default "main" }}

{{ if .Values.publishBuild }}
  {{ if .Values.goConfig.binaryTargetRepository }}
  - name: {{ .Values.namePrefix }}_binary_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}

  - name: {{ .Values.namePrefix }}_binary_spec
    type: FileSpec
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
      pattern: '{{ .Values.binaryBuildSpecPattern | default "*" }}'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}
  {{ end }}

  {{ if .Values.goConfig.moduleTargetRepository }}
  - name: {{ .Values.namePrefix }}_module_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}

  - name: {{ .Values.namePrefix }}_module_spec
    type: FileSpec
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
      pattern: '{{ .Values.moduleBuildSpecPattern | default "*" }}'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}
  {{ end }}

{{ end }}


pipelines:
  - name: {{ .Values.namePrefix }}_go_ci
    steps:
    {{ if .Values.goConfig.binaryTargetRepository }}
      - name: build
        type: GoBuild
        configuration:
          affinityGroup: {{ .Values.namePrefix }}_go_binary_ci
          environmentVariables:
            JFROG_CLI_BUILD_NAME: {{ .Values.namePrefix }}_go_binary_ci
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          integrations:
            - name: {{ .Values.artIntegration }}
          inputResources:
            - name: {{ .Values.namePrefix }}_repo
        {{ if .Values.goConfig.command }}
          goCommand: {{ .Values.goConfig.command }}
        {{ end }}
        {{ if .Values.goConfig.sourceLocation }}
          sourceLocation: {{ .Values.goConfig.sourceLocation }}
        {{ end }}
        {{ if .Values.goConfig.resolverRepo }}
          resolverRepo: {{ .Values.goConfig.resolverRepo }}
        {{ end }}
        {{ if .Values.goConfig.outputLocation }}
          outputLocation: {{ .Values.goConfig.outputLocation }}
        {{ end }}
        {{ if .Values.goConfig.outputFile }}
          outputFile: {{ .Values.goConfig.outputFile }}
        {{ end }}

      - name: publish
        type: GoPublishBinary
        configuration:
          affinityGroup: {{ .Values.namePrefix }}_go_binary_ci
          environmentVariables:
            JFROG_CLI_BUILD_NAME: {{ .Values.namePrefix }}_go_binary_ci
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          integrations:
            - name: {{ .Values.artIntegration }}
          inputSteps:
            - name: build
        {{ if .Values.publishBuild }}
          outputResources:
            - name: {{ .Values.namePrefix }}_binary_info
            - name: {{ .Values.namePrefix }}_binary_spec
        {{ end }}
        {{ if .Values.publishBuild }}
          autoPublishBuildInfo: true
        {{ end }}
        {{ if and .Values.scanBuild .Values.publishBuild }}
          forceXrayScan: true
        {{ end }}
          targetRepository: {{ .Values.goConfig.binaryTargetRepository }}

      {{ if .Values.publishBuild }}
        execution:
          onSuccess:
            - write_output {{ .Values.namePrefix }}_binary_spec buildName="${JFROG_CLI_BUILD_NAME}"
            - write_output {{ .Values.namePrefix }}_binary_spec buildNumber="${JFROG_CLI_BUILD_NUMBER}"
      {{ end }}
    {{ end }}

    {{ if .Values.goConfig.moduleTargetRepository }}
      - name: module
        type: GoPublishModule
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: {{ .Values.namePrefix }}_go_module_ci
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          integrations:
            - name: {{ .Values.artIntegration }}
          inputResources:
            - name: {{ .Values.namePrefix }}_repo
        {{ if .Values.publishBuild }}
          outputResources:
            - name: {{ .Values.namePrefix }}_module_info
            - name: {{ .Values.namePrefix }}_module_spec
        {{ end }}
        {{ if .Values.goConfig.sourceLocation }}
          sourceLocation: {{ .Values.goConfig.sourceLocation }}
        {{ end }}
        {{ if .Values.goConfig.version }}
          version: {{ .Values.goConfig.version }}
        {{ end }}
          targetRepository: {{ .Values.goConfig.moduleTargetRepository }}
        {{ if .Values.goConfig.resolverRepo }}
          resolverRepo: {{ .Values.goConfig.resolverRepo }}
        {{ end }}
        {{ if .Values.publishBuild }}
          autoPublishBuildInfo: true
        {{ end }}
        {{ if and .Values.scanBuild .Values.publishBuild }}
          forceXrayScan: true
        {{ end }}
      {{ if .Values.publishBuild }}
        execution:
          onSuccess:
            - write_output {{ .Values.namePrefix }}_module_spec buildName="${JFROG_CLI_BUILD_NAME}"
            - write_output {{ .Values.namePrefix }}_module_spec buildNumber="${JFROG_CLI_BUILD_NUMBER}"
      {{ end }}
    {{ end }}
