resources:
  - name: Environments_WF_009_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: first_Environments_WF_009
      buildName: 'name'
      buildNumber: '1'

pipelines:
  - name: Environments_WF_009
    steps:
      - name: Environments_WF_009
        type: Bash
        configuration:
          inputResources:
            - name: Environments_WF_009_BuildInfo
        execution:
          onExecute:
            - echo "step_1"
