resources:
  - name: utp_deployment_incoming_webhook_pipelines
    type: IncomingWebhook
    configuration:
      webhookName: utp_deployment
  - name: pipelines_utp_bitbucket
    type: GitRepo
    configuration:
      path: pip/controlplane
      gitProvider: JFrog_bitbucket
      branches:
        include: test1
      buildOn:
        branchDelete: true
pipelines:
 - name: my_pipe_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: pipelines_utp_bitbucket
        execution:
          onExecute:
            - echo "executing step_1"
