resources:
  - name: P_PS_10509_fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-automation-generic-local_10509/package-lock.json"
pipelines:
#  - name: P_PS_10509_001
#    steps:
#      - name: P_PS_10509_001
#        type: UploadArtifact
#        configuration:
#          targetPath: "test-automation-generic-local/tool/"
#          integrations:
#            - name: s_artifactory
#          inputResources:
#            - name: P_PS_10509_fileSpec
  - name: P_PS_10509_001
    steps:
      - name: P_PS_10509_001
        type: Bash
        configuration:
          environmentVariables:
            FORCE_RUN: 'true'
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - ls 
            - jfrog rt upload steplet.json pipelines-installers/installer/steplet.json
