resources:
  - name: utp_deployment_incoming_webhook_pipelines
    type: IncomingWebhook
    configuration:
      webhookName: utp_deployment
  - name: pipelines_utp_bitbucket
    type: GitRepo
    configuration:
      path: pip/controlplane
      gitProvider: JFrog_bitbucket
      branches:
        include: test1
      buildOn:
        branchDelete: true
pipelines:
  - name: P_PS_10509_001
    steps:
      - name: P_PS_10509_001
        type: UploadArtifact
        configuration:
          targetPath: "test-automation-generic-local-10509/tool/"
          integrations:
            - name: s_artifactory
          inputResources:
            - name: pipelines_utp_bitbucket
