resources:
  - name: pipelines_utp_bitbucket
    type: GitRepo
    configuration:
      path: nitind123/newTemplates
      gitProvider: gitad
      branches:
        include: test1
      buildOn:
        branchDelete: true
pipelines:
  - name: my_pipe_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: pipelines_utp_bitbucket
        execution:
          onExecute:
            - echo "executing step_1"
