template: true
valuesFilePath: ../values/gitRepoValues.yml

resources:
  - name: S_NpmPublish_5933_010_GitRepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: {{ .Values.GitHub.Org_test_Automation_bash.path }}
      branches:
        include: {{gitBranch}}
  - name: S_NpmPublish_5933_010_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory

pipelines:
  - name: pipeline_S_NpmPublish_5933_010
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NUMBER: ${run_id}
      outputResources:
        - name: S_NpmPublish_5933_010_BuildInfo
    steps:
      - name: S_NpmPublish_5933_010_1
        type: NpmBuild
        configuration:
          sourceLocation: "tests/npm"
          resolverRepo: "test-automation-npm-remote"
          inputResources:
            - name: S_NpmPublish_5933_010_GitRepo
          integrations:
            - name: s_artifactory
        execution:
          onStart:
            - replace_envs ${res_S_NpmPublish_5933_010_GitRepo_resourcePath}/tests/npm/package.json
      - name: S_NpmPublish_5933_010_2
        type: NpmPublish
        configuration:
          autoPublishBuildInfo: true
          deployerRepo: "test-automation-npm-local"
          inputSteps:
            - name: S_NpmPublish_5933_010_1
          integrations:
            - name: s_artifactory
      - name: S_NpmPublish_5933_010_3
        type: Bash
        configuration:
          inputSteps:
            - name: S_NpmPublish_5933_010_2
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - jfrog rt curl -XGET /api/build/${JFROG_CLI_BUILD_NAME}/${JFROG_CLI_BUILD_NUMBER} -o ${step_tmp_dir}/response
            - jfrog rt curl -XDELETE /api/build/${JFROG_CLI_BUILD_NAME}?buildNumbers=${JFROG_CLI_BUILD_NUMBER}&artifacts=1
            - if [ "$res_S_NpmPublish_5933_010_BuildInfo_buildName" != "${JFROG_CLI_BUILD_NAME}" ] ; then return 1; fi
            - if [ "$res_S_NpmPublish_5933_010_BuildInfo_buildNumber" != "${JFROG_CLI_BUILD_NUMBER}" ] ; then return 1; fi
