resources:
  - name: artifact_test
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepikaArt
      repositories:
        - example-repo-local
      artifactPath:
        include:
          - tools/*
        exclude:
          - tools/exclude/*
      buildOn:
        deployed: true
      branches:
        include: artifactResource
        exclude: master
pipelines:
  - name: P_PS_10509_0011
    steps:
      - name: P_PS_10509_0011
        type: UploadArtifact
        configuration:
          targetPath: "example-repo-local/tool/"
          integrations:
            - name: s_artifactory
          inputResources:
            - name: artifact_test      
