name: parent
description: invokes another task
source: bitbucketapsnew.jfrogdev.org/PIPA/Org_test_Automation_bash
input:
  - name: taskPath
    description: points to the nested task to invoke by absolute path
execution:
  - task: ${IN_taskPath}
    id: nested-hello-task
    repository: ${IN_taskRepo}
    input:
      target: "parent execution"

hooks:
  onStepSuccess:
    - write-output "parent success"
  onStepComplete:
    - write-output "parent complete"
  onStepFailure:
    - write-output "parent failure"