include:
  template: nameSpace10767/nameSpace10767/0.0.0
valuesFilePath: ./values.yml
pipelines:
  - name: PS_Sync_10767_3
    steps:
      - name: PS_Sync_10767_3
        type: Bash
        execution:
          onExecute:
            - cd /tmp
            - mkdir -p "node_modules/@jfrog-pipelines"
            - echo "test" >> node_modules/@jfrog-pipelines/test.txt
            - add_pipeline_files node_modules/@jfrog-pipelines jfrog_pipelines_packages_cache
