template:
  namespace: nameSpace10767
  name: nameSpace10767
  version: 0.0.0
  development: false

pipelines:
  - name: {{ .Values.Pipeline.name | default "Pipeline_10767" }}
    steps:
      - name: {{ .Values.Pipeline.name }}
        type: Bash
        configuration:
          environmentVariables:
            env1: {{gitBranch}}
            env2: {{.jfrog-pipelines.sourceRepository}}
        execution:
          onExecute:
            - echo  {{ .Values.Pipeline.name }}
